version: "3.8"
services:
  tiwap:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/tiwap
    depends_on:
      - db
  db:
    image: "mongo:4.4"
    environment:
      - MONGO_INITDB_DATABASE=TIWAP
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - "27017:27017"

  zap:
    user: root
    image: zaproxy/zap-stable
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./zap-config:/zap/wrk
    #entrypoint: >
      #zap-baseline.py -t https://localhost:5000 -r /zap/wrk/scan-report.html

networks:
  app-network:
    driver: bridge
